# Generated by Django 2.2.5 on 2019-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='user_email')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
